// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// How a language spells comments.
///
/// `None` on both means the format has none. That is a fact worth stating
/// rather than papering over: strict JSON genuinely cannot carry a comment, and
/// inserting `//` would produce a document that no longer parses.
class CommentStyle {
  final String? line;
  final String? blockStart;
  final String? blockEnd;

  /// Shown to the user when the format has no comment syntax, explaining why
  /// the operation is unavailable.
  final String? unsupportedNote;

  const CommentStyle({
    this.line,
    this.blockStart,
    this.blockEnd,
    this.unsupportedNote,
  });

  @override
  int get hashCode =>
      line.hashCode ^
      blockStart.hashCode ^
      blockEnd.hashCode ^
      unsupportedNote.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommentStyle &&
          runtimeType == other.runtimeType &&
          line == other.line &&
          blockStart == other.blockStart &&
          blockEnd == other.blockEnd &&
          unsupportedNote == other.unsupportedNote;
}
