// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `register_defaults`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

CommandRegistry getCommandRegistry() =>
    RustLib.instance.api.crateApiCommandsGetCommandRegistry();

class CommandDescriptor {
  final String id;
  final String title;
  final String category;
  final String? icon;
  final String? shortcut;
  final bool? toggled;

  /// The ID of the input panel widget to display, if this command needs one.
  final String? panelId;

  /// The ID of the action to execute, if this command executes immediately.
  final String? actionId;

  const CommandDescriptor({
    required this.id,
    required this.title,
    required this.category,
    this.icon,
    this.shortcut,
    this.toggled,
    this.panelId,
    this.actionId,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      category.hashCode ^
      icon.hashCode ^
      shortcut.hashCode ^
      toggled.hashCode ^
      panelId.hashCode ^
      actionId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommandDescriptor &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          category == other.category &&
          icon == other.icon &&
          shortcut == other.shortcut &&
          toggled == other.toggled &&
          panelId == other.panelId &&
          actionId == other.actionId;
}

class CommandRegistry {
  final List<CommandDescriptor> commands;

  const CommandRegistry({required this.commands});

  List<CommandDescriptor> getAll() =>
      RustLib.instance.api.crateApiCommandsCommandRegistryGetAll(that: this);

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<CommandRegistry> newInstance() =>
      RustLib.instance.api.crateApiCommandsCommandRegistryNew();

  List<CommandDescriptor> search({required String query}) => RustLib
      .instance
      .api
      .crateApiCommandsCommandRegistrySearch(that: this, query: query);

  @override
  int get hashCode => commands.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommandRegistry &&
          runtimeType == other.runtimeType &&
          commands == other.commands;
}
