// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_comment_symbols`

Future<String> properCase({required String input, required bool blend}) =>
    RustLib.instance.api.crateApiEditOpsProperCase(input: input, blend: blend);

Future<String> sentenceCase({required String input, required bool blend}) =>
    RustLib.instance.api.crateApiEditOpsSentenceCase(
      input: input,
      blend: blend,
    );

Future<String> invertCase({required String input}) =>
    RustLib.instance.api.crateApiEditOpsInvertCase(input: input);

Future<String> randomCase({required String input}) =>
    RustLib.instance.api.crateApiEditOpsRandomCase(input: input);

Future<String> convertEol({required String input, required String eolType}) =>
    RustLib.instance.api.crateApiEditOpsConvertEol(
      input: input,
      eolType: eolType,
    );

Future<String> trimTrailing({required String input}) =>
    RustLib.instance.api.crateApiEditOpsTrimTrailing(input: input);

Future<String> trimLeading({required String input}) =>
    RustLib.instance.api.crateApiEditOpsTrimLeading(input: input);

Future<String> trimBoth({required String input}) =>
    RustLib.instance.api.crateApiEditOpsTrimBoth(input: input);

Future<String> eolToSpace({required String input}) =>
    RustLib.instance.api.crateApiEditOpsEolToSpace(input: input);

Future<String> trimBothAndEolToSpace({required String input}) =>
    RustLib.instance.api.crateApiEditOpsTrimBothAndEolToSpace(input: input);

Future<String> tabToSpace({required String input, required BigInt tabWidth}) =>
    RustLib.instance.api.crateApiEditOpsTabToSpace(
      input: input,
      tabWidth: tabWidth,
    );

Future<String> spaceToTab({
  required String input,
  required BigInt tabWidth,
  required bool leadingOnly,
}) => RustLib.instance.api.crateApiEditOpsSpaceToTab(
  input: input,
  tabWidth: tabWidth,
  leadingOnly: leadingOnly,
);

Future<String> toggleSingleLineComment({
  required String input,
  required String extension_,
}) => RustLib.instance.api.crateApiEditOpsToggleSingleLineComment(
  input: input,
  extension_: extension_,
);

Future<String> blockComment({
  required String input,
  required String extension_,
}) => RustLib.instance.api.crateApiEditOpsBlockComment(
  input: input,
  extension_: extension_,
);

Future<String> blockUncomment({
  required String input,
  required String extension_,
}) => RustLib.instance.api.crateApiEditOpsBlockUncomment(
  input: input,
  extension_: extension_,
);

Future<String> singleLineComment({
  required String input,
  required String extension_,
}) => RustLib.instance.api.crateApiEditOpsSingleLineComment(
  input: input,
  extension_: extension_,
);

Future<String> singleLineUncomment({
  required String input,
  required String extension_,
}) => RustLib.instance.api.crateApiEditOpsSingleLineUncomment(
  input: input,
  extension_: extension_,
);

String applyEditOp({
  required String input,
  required String opId,
  required String extension_,
  required BigInt tabWidth,
}) => RustLib.instance.api.crateApiEditOpsApplyEditOp(
  input: input,
  opId: opId,
  extension_: extension_,
  tabWidth: tabWidth,
);
