// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'search.dart';

// These functions are ignored because they are not marked as `pub`: `apply`, `base_line`, `build_edits`, `do_delete`, `do_insert`, `get_line_visual`, `get_logical`, `new`, `prepare_edit`, `record`, `reset_after_save`, `u16_len`, `u16_to_byte`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Op`, `UndoEntry`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<EditSession>>
abstract class EditSession implements RustOpaqueInterface {
  /// Begin grouping subsequent mutations into a single undo step.
  void beginGroup();

  /// Break typing coalescing (call on caret moves, clicks, focus changes) so
  /// the next insert starts a fresh undo step.
  void breakCoalescing();

  bool canRedo();

  bool canUndo();

  /// The full current document text (base + overlay), visual lines joined by
  /// '\n'. Used to capture scratch-document content for persistence.
  String contentString();

  /// Fast copy of the entire document to the system clipboard on the Rust side.
  /// Returns the UTF-16 character count of the copied text.
  BigInt copyToClipboard();

  /// Create a scratch file at `path` containing `content` (creating parent
  /// dirs), then open a session over it. Keeps document IO on the Rust side so
  /// Dart never writes files itself. Used to rehydrate persisted scratch docs.
  static EditSession createScratch({
    required String path,
    required String content,
  }) => RustLib.instance.api.crateApiEditSessionEditSessionCreateScratch(
    path: path,
    content: content,
  );

  CaretPos delete({
    required BigInt srow,
    required BigInt scol,
    required BigInt erow,
    required BigInt ecol,
  });

  /// Finalize the current group.
  void endGroup();

  /// Find every match whose start row is in `[from_row, to_row)`.
  ///
  /// The scan itself reaches `SEARCH_WINDOW_OVERLAP_ROWS` rows past
  /// `to_row` so a multi-line match straddling the boundary is still found,
  /// but such a match is only returned by the window its *start* falls in.
  /// Consecutive windows therefore tile exactly, with no duplicates.
  Future<List<MatchSpan>> findInRows({
    required SearchQuery query,
    required BigInt fromRow,
    required BigInt toRow,
  });

  CaretPos insert({
    required BigInt row,
    required BigInt col,
    required String text,
  });

  bool isDirty();

  String line({required BigInt vrow});

  BigInt lineCount();

  static EditSession open({required String path}) =>
      RustLib.instance.api.crateApiEditSessionEditSessionOpen(path: path);

  String path();

  CaretPos? redo();

  void refresh();

  /// Replace the entire document with `text`, recorded as a single undoable
  /// step (delete-all + insert). Used by transforms like the MIME tools that
  /// rewrite the whole buffer. Returns the caret past the inserted text.
  CaretPos replaceAll({required String text});

  void save();

  void saveAs({required String newPath});

  /// Calculate selection character count extremely fast (combining small range exact counting and large range O(1) estimation)
  BigInt selectionCharCount({
    required BigInt r1,
    required BigInt c1,
    required BigInt r2,
    required BigInt c2,
  });

  /// Set whether consecutive single-character typing coalesces into one undo
  /// step (true) or each keystroke is its own step (false).
  void setCoalesceUndo({required bool on_});

  CaretPos? undo();
}

/// Where the caret should sit after an operation. Columns are counted in
/// UTF-16 code units, matching the Dart/Flutter renderer (1 column == 1
/// monospace cell for the BMP, which covers all normal text and code).
class CaretPos {
  final BigInt row;
  final BigInt col;

  const CaretPos({required this.row, required this.col});

  @override
  int get hashCode => row.hashCode ^ col.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CaretPos &&
          runtimeType == other.runtimeType &&
          row == other.row &&
          col == other.col;
}
