// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `read_bytes`, `save_edits_impl`, `scan_file`

/// Copy arbitrary text to the system clipboard. Keeps clipboard access on the
/// Rust side (used by "Copy file name" / "Copy file path").
void copyTextToClipboard({required String text}) =>
    RustLib.instance.api.crateApiFileManagerCopyTextToClipboard(text: text);

/// The final path component (file name with extension), e.g. `/a/b/c.txt` -> `c.txt`.
String baseName({required String path}) =>
    RustLib.instance.api.crateApiFileManagerBaseName(path: path);

Future<String?> pickFile() =>
    RustLib.instance.api.crateApiFileManagerPickFile();

/// Save-as dialog. Returns the chosen path, or None if cancelled.
Future<String?> pickSaveFile({required String defaultName}) => RustLib
    .instance
    .api
    .crateApiFileManagerPickSaveFile(defaultName: defaultName);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FileBuffer>>
abstract class FileBuffer implements RustOpaqueInterface {
  Uint64List get lineOffsets;

  String get path;

  BigInt get size;

  set lineOffsets(Uint64List lineOffsets);

  set path(String path);

  set size(BigInt size);

  BigInt getLineCount();

  static FileBuffer open({required String path}) =>
      RustLib.instance.api.crateApiFileManagerFileBufferOpen(path: path);

  String readLine({required BigInt index});

  LineChunk readLineChunk({required BigInt startLine, required BigInt count});

  void refresh();

  void saveEdits({required List<LineEdit> edits});

  /// Write the edited document to a new path, rebinding this buffer to it.
  void saveEditsAs({required String newPath, required List<LineEdit> edits});
}

class LineChunk {
  final String content;
  final BigInt startLine;
  final BigInt endLine;
  final BigInt byteStart;
  final BigInt byteEnd;

  const LineChunk({
    required this.content,
    required this.startLine,
    required this.endLine,
    required this.byteStart,
    required this.byteEnd,
  });

  @override
  int get hashCode =>
      content.hashCode ^
      startLine.hashCode ^
      endLine.hashCode ^
      byteStart.hashCode ^
      byteEnd.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LineChunk &&
          runtimeType == other.runtimeType &&
          content == other.content &&
          startLine == other.startLine &&
          endLine == other.endLine &&
          byteStart == other.byteStart &&
          byteEnd == other.byteEnd;
}

class LineEdit {
  final BigInt row;
  final List<String> lines;

  const LineEdit({required this.row, required this.lines});

  @override
  int get hashCode => row.hashCode ^ lines.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LineEdit &&
          runtimeType == other.runtimeType &&
          row == other.row &&
          lines == other.lines;
}
