// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply_op`, `apply_splice`, `contiguous`, `from_file_buffer`, `merge_around`, `record`, `reset_after_save`, `save_impl`, `sniff_binary`, `split_at`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Op`, `Piece`, `Source`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`

/// Sniff the first ~8 KB of `path` and report whether it looks binary. Drives
/// the "open binary files in hex mode" behavior on the Dart side.
bool isBinaryFile({required String path}) =>
    RustLib.instance.api.crateApiHexSessionIsBinaryFile(path: path);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<HexSession>>
abstract class HexSession implements RustOpaqueInterface {
  /// Begin grouping subsequent mutations into a single undo step.
  void beginGroup();

  /// Break typing coalescing (call on caret moves, clicks, focus changes) so
  /// the next edit starts a fresh undo step.
  void breakCoalescing();

  bool canRedo();

  bool canUndo();

  /// Delete `len` bytes at `offset` (clamped). Returns the caret offset, which
  /// stays at `offset`.
  BigInt delete({required BigInt offset, required BigInt len});

  /// Finalize the current group.
  void endGroup();

  /// Insert `bytes` at `offset`, shifting following bytes. Returns the caret
  /// offset just past the inserted bytes.
  BigInt insertBytes({required BigInt offset, required List<int> bytes});

  bool isDirty();

  /// Current total document length, in bytes.
  BigInt len();

  /// Absolute byte ranges within `[offset, offset+len)` that have been edited
  /// (i.e. come from the `added` buffer). Deletions leave no bytes and are not
  /// reported. Adjacent ranges are not coalesced across the window boundary.
  List<ByteRange> modifiedRanges({required BigInt offset, required BigInt len});

  static HexSession open({required String path}) =>
      RustLib.instance.api.crateApiHexSessionHexSessionOpen(path: path);

  /// Overwrite the bytes starting at `offset` with `bytes` (length unchanged
  /// where possible). Overwriting past the end appends. Returns the caret
  /// offset just past the written bytes.
  BigInt overwriteBytes({required BigInt offset, required List<int> bytes});

  String path();

  /// The current (post-edit) bytes in `[offset, offset+len)`, clamped to the
  /// document end. Walks only the pieces overlapping the window; base pieces
  /// are read from disk on demand, so the whole file is never loaded.
  /// Bridged to Dart as `Uint8List`.
  Uint8List readWindow({required BigInt offset, required BigInt len});

  BigInt? redo();

  void save();

  void saveAs({required String newPath});

  BigInt? undo();
}

/// An edited byte range, in absolute offsets. Returned by [`HexSession::modified_ranges`]
/// so the UI can highlight bytes that differ from the base file.
class ByteRange {
  final BigInt start;
  final BigInt len;

  const ByteRange({required this.start, required this.len});

  @override
  int get hashCode => start.hashCode ^ len.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ByteRange &&
          runtimeType == other.runtimeType &&
          start == other.start &&
          len == other.len;
}
