// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `decode_base64_json`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

JwtDecodeResult decodeJwt({required String token, String? secret}) =>
    RustLib.instance.api.crateApiJwtDecodeJwt(token: token, secret: secret);

String encodeJwt({
  required String header,
  required String payload,
  required String secret,
}) => RustLib.instance.api.crateApiJwtEncodeJwt(
  header: header,
  payload: payload,
  secret: secret,
);

class JwtDecodeResult {
  final String header;
  final String payload;
  final String signature;
  final bool isValid;
  final String? error;

  const JwtDecodeResult({
    required this.header,
    required this.payload,
    required this.signature,
    required this.isValid,
    this.error,
  });

  @override
  int get hashCode =>
      header.hashCode ^
      payload.hashCode ^
      signature.hashCode ^
      isValid.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is JwtDecodeResult &&
          runtimeType == other.runtimeType &&
          header == other.header &&
          payload == other.payload &&
          signature == other.signature &&
          isValid == other.isValid &&
          error == other.error;
}
