// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `encode_full`, `per_line`, `try_per_line`

/// Base64-encode `input`.
///
/// - `padding`: emit `=` padding (standard) vs. no padding.
/// - `unix_eol`: normalize CRLF/CR to LF before encoding.
/// - `by_line`: encode each line independently, preserving line breaks.
String base64Encode({
  required String input,
  required bool padding,
  required bool unixEol,
  required bool byLine,
}) => RustLib.instance.api.crateApiMimeToolsBase64Encode(
  input: input,
  padding: padding,
  unixEol: unixEol,
  byLine: byLine,
);

/// Base64-decode `input`, returning the bytes as (lossy) UTF-8 text.
///
/// - `strict`: reject trailing bits / disallow non-canonical input and require
///   padding. Non-strict mode tolerates whitespace, newlines and missing
///   padding (handy for pasted, wrapped blobs).
/// - `by_line`: decode each line independently.
String base64Decode({
  required String input,
  required bool strict,
  required bool byLine,
}) => RustLib.instance.api.crateApiMimeToolsBase64Decode(
  input: input,
  strict: strict,
  byLine: byLine,
);

/// Quoted-printable encode.
String qpEncode({required String input}) =>
    RustLib.instance.api.crateApiMimeToolsQpEncode(input: input);

/// Quoted-printable decode (robust parse mode tolerates minor violations).
String qpDecode({required String input}) =>
    RustLib.instance.api.crateApiMimeToolsQpDecode(input: input);

/// URL / percent-encode `input` per `variant`. `by_line` encodes each line
/// independently (so line breaks survive).
String urlEncode({
  required String input,
  required UrlEncodeVariant variant,
  required bool byLine,
}) => RustLib.instance.api.crateApiMimeToolsUrlEncode(
  input: input,
  variant: variant,
  byLine: byLine,
);

/// Percent-decode `input` to (lossy) UTF-8 text.
String urlDecode({required String input}) =>
    RustLib.instance.api.crateApiMimeToolsUrlDecode(input: input);

/// Decode a SAML request/response token: optional URL-decode, base64-decode,
/// then (for the HTTP-Redirect binding) raw-DEFLATE inflate. If inflation
/// fails the token is assumed already-inflated (HTTP-POST binding) and the
/// base64-decoded XML is returned as-is.
String samlDecode({required String input}) =>
    RustLib.instance.api.crateApiMimeToolsSamlDecode(input: input);

/// Which characters a URL encode pass escapes.
enum UrlEncodeVariant {
  /// RFC 1738 style: keep unreserved `A-Za-z0-9` and `-_.`; escape the rest
  /// (spaces become `%20`).
  rfc1738,

  /// Extended (JS `encodeURIComponent`-like): additionally keep `!~*'()`.
  extended,

  /// Full: escape every byte, including alphanumerics.
  full,
}
