// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `base_dir`, `db_path`

/// The app data directory, created if missing.
String appDataDir() => RustLib.instance.api.crateApiPathsAppDataDir();

/// The scratch directory for transient documents, created if missing.
String scratchDir() => RustLib.instance.api.crateApiPathsScratchDir();
