// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `MatchSpan`, `SpanScope`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

/// Expand `\n \r \t \0 \\ \xHH \uXXXX`. An unrecognized escape is an error
/// rather than a silent literal, so a typo surfaces in the panel.
Future<String> unescapeExtended({required String s}) =>
    RustLib.instance.api.crateApiSearchUnescapeExtended(s: s);

/// Lower any search mode to a single regex. This is the one place a mode is
/// interpreted; every caller goes through it.
Future<Regex> compile({required SearchQuery query}) =>
    RustLib.instance.api.crateApiSearchCompile(query: query);

/// Build the replacement text for one match. Capture references are honored
/// only in Regex mode; Normal mode keeps `$1` literal, as Notepad++ does.
Future<String> expandReplacement({
  required SearchMode mode,
  required Captures caps,
  required String template,
}) => RustLib.instance.api.crateApiSearchExpandReplacement(
  mode: mode,
  caps: caps,
  template: template,
);

/// Cheap validity check for the panel to call on every keystroke. Returns the
/// error message when the query cannot compile, or None when it is usable.
String? validateQuery({required SearchQuery query}) =>
    RustLib.instance.api.crateApiSearchValidateQuery(query: query);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Captures>>
abstract class Captures implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Regex>>
abstract class Regex implements RustOpaqueInterface {}

/// How a search pattern is interpreted. Mirrors Notepad++'s Search Mode.
enum SearchMode {
  /// Literal text.
  normal,

  /// Literal text after `\n \r \t \0 \\ \xHH \uXXXX` expansion.
  extended,

  /// A regular expression.
  regex,
}

class SearchQuery {
  final String pattern;
  final SearchMode mode;
  final bool matchCase;
  final bool wholeWord;

  /// Regex mode only: `.` also matches '\n'.
  final bool dotMatchesNewline;

  const SearchQuery({
    required this.pattern,
    required this.mode,
    required this.matchCase,
    required this.wholeWord,
    required this.dotMatchesNewline,
  });

  @override
  int get hashCode =>
      pattern.hashCode ^
      mode.hashCode ^
      matchCase.hashCode ^
      wholeWord.hashCode ^
      dotMatchesNewline.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchQuery &&
          runtimeType == other.runtimeType &&
          pattern == other.pattern &&
          mode == other.mode &&
          matchCase == other.matchCase &&
          wholeWord == other.wholeWord &&
          dotMatchesNewline == other.dotMatchesNewline;
}
