// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `compile`, `expand_replacement`

/// Expand `\n \r \t \0 \\ \xHH \uXXXX`. An unrecognized escape is an error
/// rather than a silent literal, so a typo surfaces in the panel.
Future<String> unescapeExtended({required String s}) =>
    RustLib.instance.api.crateApiSearchUnescapeExtended(s: s);

/// Cheap validity check for the panel to call on every keystroke. Returns the
/// error message when the query cannot compile, or None when it is usable.
String? validateQuery({required SearchQuery query}) =>
    RustLib.instance.api.crateApiSearchValidateQuery(query: query);

/// A match, in the editor's coordinate system. Columns are UTF-16 code units.
class MatchSpan {
  final BigInt startRow;
  final BigInt startCol;
  final BigInt endRow;
  final BigInt endCol;

  const MatchSpan({
    required this.startRow,
    required this.startCol,
    required this.endRow,
    required this.endCol,
  });

  @override
  int get hashCode =>
      startRow.hashCode ^ startCol.hashCode ^ endRow.hashCode ^ endCol.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MatchSpan &&
          runtimeType == other.runtimeType &&
          startRow == other.startRow &&
          startCol == other.startCol &&
          endRow == other.endRow &&
          endCol == other.endCol;
}

/// How a search pattern is interpreted. Mirrors Notepad++'s Search Mode.
enum SearchMode {
  /// Literal text.
  normal,

  /// Literal text after `\n \r \t \0 \\ \xHH \uXXXX` expansion.
  extended,

  /// A regular expression.
  regex,
}

class SearchQuery {
  final String pattern;
  final SearchMode mode;
  final bool matchCase;
  final bool wholeWord;

  /// Regex mode only: `.` also matches '\n'.
  final bool dotMatchesNewline;

  const SearchQuery({
    required this.pattern,
    required this.mode,
    required this.matchCase,
    required this.wholeWord,
    required this.dotMatchesNewline,
  });

  @override
  int get hashCode =>
      pattern.hashCode ^
      mode.hashCode ^
      matchCase.hashCode ^
      wholeWord.hashCode ^
      dotMatchesNewline.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchQuery &&
          runtimeType == other.runtimeType &&
          pattern == other.pattern &&
          mode == other.mode &&
          matchCase == other.matchCase &&
          wholeWord == other.wholeWord &&
          dotMatchesNewline == other.dotMatchesNewline;
}

/// A row/column range limiting a search ("In selection").
class SpanScope {
  final BigInt startRow;
  final BigInt startCol;
  final BigInt endRow;
  final BigInt endCol;

  const SpanScope({
    required this.startRow,
    required this.startCol,
    required this.endRow,
    required this.endCol,
  });

  @override
  int get hashCode =>
      startRow.hashCode ^ startCol.hashCode ^ endRow.hashCode ^ endCol.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SpanScope &&
          runtimeType == other.runtimeType &&
          startRow == other.startRow &&
          startCol == other.startCol &&
          endRow == other.endRow &&
          endCol == other.endCol;
}
