// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'structured.dart';

// These functions are ignored because they are not marked as `pub`: `c`, `ensure_column`, `init_schema`, `join_rows`, `split_rows`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DocRow`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AppStore>>
abstract class AppStore implements RustOpaqueInterface {
  /// Fetch a setting value, or None if unset.
  String? getSetting({required String key});

  /// Load the persisted tabs in tab order, after purging any atMidnight docs
  /// whose creation day is before `today_epoch_day` (a midnight has passed).
  List<DocRecord> loadSession({required PlatformInt64 todayEpochDay});

  /// Open (creating if needed) the store at the OS-correct data location and
  /// ensure the schema exists.
  static AppStore open() => RustLib.instance.api.crateApiStoreAppStoreOpen();

  /// Open a store at an explicit path.
  ///
  /// The location seam. [`open`](Self::open) is what the app calls; this is
  /// for anything that must not touch the user's real session — widget tests
  /// pumping the app shell against a seeded database, and a portable mode
  /// keeping its state beside the binary.
  ///
  /// Without it a widget test that exercises session restore would read and
  /// overwrite the tabs of whoever ran the suite.
  static AppStore openAt({required String path}) =>
      RustLib.instance.api.crateApiStoreAppStoreOpenAt(path: path);

  /// Replace the whole persisted tab set with `docs`, in the given order. The
  /// caller passes exactly the tabs it wants restored next launch (e.g.
  /// excluding onAppClose docs at shutdown).
  void saveSession({required List<DocRecord> docs});

  /// Upsert a setting value.
  void setSetting({required String key, required String value});
}

/// A persisted tab, mirrored across the frb boundary. Dart builds these from its
/// tab list; `scratch_content` is `Some` only for transient documents.
class DocRecord {
  final String id;
  final String displayName;
  final String path;
  final bool isTransient;
  final String contentType;
  final String extension_;

  /// One of "off" | "onAppClose" | "atMidnight" (matches the Dart enum name).
  final String autoDelete;
  final String viewMode;
  final double fontRead;
  final double fontTail;
  final double fontEdit;
  final String? scratchContent;

  /// Epoch day the doc was created (for the atMidnight purge). 0 for real files.
  final PlatformInt64 createdDay;
  final int tabOrder;
  final bool isActive;

  /// Rows the user has collapsed, as fold start rows. Stored as one text
  /// column; see [`join_rows`].
  final Uint32List collapsedFolds;

  /// The format the user pinned this document to, or `None` to let detection
  /// decide. Persisted as the language's stable id, empty for `None`.
  final StructuredLanguage? languageOverride;

  const DocRecord({
    required this.id,
    required this.displayName,
    required this.path,
    required this.isTransient,
    required this.contentType,
    required this.extension_,
    required this.autoDelete,
    required this.viewMode,
    required this.fontRead,
    required this.fontTail,
    required this.fontEdit,
    this.scratchContent,
    required this.createdDay,
    required this.tabOrder,
    required this.isActive,
    required this.collapsedFolds,
    this.languageOverride,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      displayName.hashCode ^
      path.hashCode ^
      isTransient.hashCode ^
      contentType.hashCode ^
      extension_.hashCode ^
      autoDelete.hashCode ^
      viewMode.hashCode ^
      fontRead.hashCode ^
      fontTail.hashCode ^
      fontEdit.hashCode ^
      scratchContent.hashCode ^
      createdDay.hashCode ^
      tabOrder.hashCode ^
      isActive.hashCode ^
      collapsedFolds.hashCode ^
      languageOverride.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DocRecord &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          displayName == other.displayName &&
          path == other.path &&
          isTransient == other.isTransient &&
          contentType == other.contentType &&
          extension_ == other.extension_ &&
          autoDelete == other.autoDelete &&
          viewMode == other.viewMode &&
          fontRead == other.fontRead &&
          fontTail == other.fontTail &&
          fontEdit == other.fontEdit &&
          scratchContent == other.scratchContent &&
          createdDay == other.createdDay &&
          tabOrder == other.tabOrder &&
          isActive == other.isActive &&
          collapsedFolds == other.collapsedFolds &&
          languageOverride == other.languageOverride;
}
