// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `from_domain`, `from_domain`, `to_domain`, `wire_analysis`, `wire_diagnostic`, `wire_fold`, `wire_pair_public`, `wire_pair`, `wire_row_tokens`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

/// Detect a document's format from its extension, its content type, and — for
/// unsaved documents where neither says anything — its content.
StructuredLanguage detectStructuredLanguage({
  required String extension_,
  required String contentType,
  required String sample,
}) => RustLib.instance.api.crateApiStructuredDetectStructuredLanguage(
  extension_: extension_,
  contentType: contentType,
  sample: sample,
);

/// The display name of a language.
String structuredLanguageLabel({required StructuredLanguage language}) =>
    RustLib.instance.api.crateApiStructuredStructuredLanguageLabel(
      language: language,
    );

/// The stable identifier a language is persisted under, for the per-document
/// override stored on `documents.language_override`.
String structuredLanguageId({required StructuredLanguage language}) => RustLib
    .instance
    .api
    .crateApiStructuredStructuredLanguageId(language: language);

/// The inverse of [`structured_language_id`]. `None` for anything
/// unrecognised, which the caller reads as "no override, detect instead".
StructuredLanguage? structuredLanguageFromId({required String id}) =>
    RustLib.instance.api.crateApiStructuredStructuredLanguageFromId(id: id);

/// Every language the user can pin a document to, in menu order.
List<StructuredLanguage> structuredLanguages() =>
    RustLib.instance.api.crateApiStructuredStructuredLanguages();

/// The comment syntax for a document. The detected language wins over the file
/// extension, so a YAML document saved as `.txt` still comments with `#`.
StructuredCommentStyle structuredCommentStyle({
  required StructuredLanguage language,
  required String extension_,
}) => RustLib.instance.api.crateApiStructuredStructuredCommentStyle(
  language: language,
  extension_: extension_,
);

/// Folds, pairs and diagnostics for a whole document.
StructuredAnalysis analyzeStructured({
  required String text,
  required StructuredLanguage language,
}) => RustLib.instance.api.crateApiStructuredAnalyzeStructured(
  text: text,
  language: language,
);

/// Validate a document, returning diagnostics in document order.
List<StructuredDiagnostic> validateStructured({
  required String text,
  required StructuredLanguage language,
}) => RustLib.instance.api.crateApiStructuredValidateStructured(
  text: text,
  language: language,
);

/// Tokens for a whole snippet, lexed from the top. Used for Read and Tail,
/// which render a text slice rather than an edit session.
List<StructuredRowTokens> tokenizeStructured({
  required String text,
  required StructuredLanguage language,
}) => RustLib.instance.api.crateApiStructuredTokenizeStructured(
  text: text,
  language: language,
);

/// Pretty-print or minify.
String formatStructured({
  required String text,
  required StructuredLanguage language,
  required bool pretty,
  required String indent,
}) => RustLib.instance.api.crateApiStructuredFormatStructured(
  text: text,
  language: language,
  pretty: pretty,
  indent: indent,
);

/// Escape text for embedding in a document of this format.
String escapeStructured({
  required String text,
  required StructuredLanguage language,
}) => RustLib.instance.api.crateApiStructuredEscapeStructured(
  text: text,
  language: language,
);

/// Turn escape sequences back into the characters they stand for.
String unescapeStructured({
  required String text,
  required StructuredLanguage language,
}) => RustLib.instance.api.crateApiStructuredUnescapeStructured(
  text: text,
  language: language,
);

/// The result of the whole-document pass.
class StructuredAnalysis {
  final StructuredLanguage language;
  final List<StructuredFold> folds;
  final List<StructuredPair> pairs;
  final List<StructuredDiagnostic> diagnostics;

  /// True when the document was too large to analyse. The empty lists then
  /// mean "not computed", not "nothing found".
  final bool truncated;

  const StructuredAnalysis({
    required this.language,
    required this.folds,
    required this.pairs,
    required this.diagnostics,
    required this.truncated,
  });

  @override
  int get hashCode =>
      language.hashCode ^
      folds.hashCode ^
      pairs.hashCode ^
      diagnostics.hashCode ^
      truncated.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StructuredAnalysis &&
          runtimeType == other.runtimeType &&
          language == other.language &&
          folds == other.folds &&
          pairs == other.pairs &&
          diagnostics == other.diagnostics &&
          truncated == other.truncated;
}

/// How a language spells comments. Both `line` and `block_start` being `None`
/// means the format has none — see `unsupported_note` for what to tell the user.
class StructuredCommentStyle {
  final String? line;
  final String? blockStart;
  final String? blockEnd;
  final String? unsupportedNote;

  const StructuredCommentStyle({
    this.line,
    this.blockStart,
    this.blockEnd,
    this.unsupportedNote,
  });

  @override
  int get hashCode =>
      line.hashCode ^
      blockStart.hashCode ^
      blockEnd.hashCode ^
      unsupportedNote.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StructuredCommentStyle &&
          runtimeType == other.runtimeType &&
          line == other.line &&
          blockStart == other.blockStart &&
          blockEnd == other.blockEnd &&
          unsupportedNote == other.unsupportedNote;
}

/// A validation problem, positioned so the UI can reveal it.
class StructuredDiagnostic {
  final int row;
  final int col;
  final int endRow;
  final int endCol;
  final StructuredSeverity severity;
  final String message;

  const StructuredDiagnostic({
    required this.row,
    required this.col,
    required this.endRow,
    required this.endCol,
    required this.severity,
    required this.message,
  });

  @override
  int get hashCode =>
      row.hashCode ^
      col.hashCode ^
      endRow.hashCode ^
      endCol.hashCode ^
      severity.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StructuredDiagnostic &&
          runtimeType == other.runtimeType &&
          row == other.row &&
          col == other.col &&
          endRow == other.endRow &&
          endCol == other.endCol &&
          severity == other.severity &&
          message == other.message;
}

/// A collapsible span. `start_row` stays visible when collapsed; `end_row` is
/// the last row hidden.
class StructuredFold {
  final int startRow;
  final int endRow;
  final int startCol;
  final StructuredFoldKind kind;

  /// Placeholder drawn on the collapsed row.
  final String label;

  /// Nesting depth, outermost = 0. Drives fold-to-level.
  final int level;

  const StructuredFold({
    required this.startRow,
    required this.endRow,
    required this.startCol,
    required this.kind,
    required this.label,
    required this.level,
  });

  @override
  int get hashCode =>
      startRow.hashCode ^
      endRow.hashCode ^
      startCol.hashCode ^
      kind.hashCode ^
      label.hashCode ^
      level.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StructuredFold &&
          runtimeType == other.runtimeType &&
          startRow == other.startRow &&
          endRow == other.endRow &&
          startCol == other.startCol &&
          kind == other.kind &&
          label == other.label &&
          level == other.level;
}

enum StructuredFoldKind { object, array, element, block, comment }

/// A structured format, or `PlainText` for everything else.
enum StructuredLanguage { plainText, json, json5, yaml, xml }

/// A matched delimiter pair: braces, brackets, or an XML open/close tag.
class StructuredPair {
  final int openRow;
  final int openCol;
  final int openLen;
  final int closeRow;
  final int closeCol;
  final int closeLen;

  const StructuredPair({
    required this.openRow,
    required this.openCol,
    required this.openLen,
    required this.closeRow,
    required this.closeCol,
    required this.closeLen,
  });

  @override
  int get hashCode =>
      openRow.hashCode ^
      openCol.hashCode ^
      openLen.hashCode ^
      closeRow.hashCode ^
      closeCol.hashCode ^
      closeLen.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StructuredPair &&
          runtimeType == other.runtimeType &&
          openRow == other.openRow &&
          openCol == other.openCol &&
          openLen == other.openLen &&
          closeRow == other.closeRow &&
          closeCol == other.closeCol &&
          closeLen == other.closeLen;
}

/// Every token on one row, ascending and non-overlapping.
class StructuredRowTokens {
  final int row;
  final List<StructuredToken> tokens;

  const StructuredRowTokens({required this.row, required this.tokens});

  @override
  int get hashCode => row.hashCode ^ tokens.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StructuredRowTokens &&
          runtimeType == other.runtimeType &&
          row == other.row &&
          tokens == other.tokens;
}

enum StructuredSeverity { error, warning }

/// A token as a half-open UTF-16 column range within one row.
class StructuredToken {
  final int start;
  final int end;
  final StructuredTokenKind kind;

  const StructuredToken({
    required this.start,
    required this.end,
    required this.kind,
  });

  @override
  int get hashCode => start.hashCode ^ end.hashCode ^ kind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StructuredToken &&
          runtimeType == other.runtimeType &&
          start == other.start &&
          end == other.end &&
          kind == other.kind;
}

/// What a run of characters means. Dart maps these to colours.
enum StructuredTokenKind {
  key,
  str,
  number,
  keyword,
  punctuation,
  tagName,
  attributeName,
  comment,
  text,
  cData,
  doctype,
  processingInstruction,
  entity,
  alias,
  directive,
  invalid,
}
