// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`

/// Serialise for the `settings` table.
///
/// A flat comma-separated string rather than JSON: the table is
/// `TEXT`-to-`TEXT`, there is exactly one reader, and a malformed value has to
/// be survivable anyway (see [`parse_window_geometry`]), so a format that
/// cannot half-parse is worth more here than one that is self-describing.
String encodeWindowGeometry({required WindowGeometry geometry}) =>
    RustLib.instance.api.crateApiWindowEncodeWindowGeometry(geometry: geometry);

/// Parse a stored geometry, or `None` if it is not one.
///
/// Returning `None` rather than a default matters: the caller must be able to
/// tell "no stored geometry" from "a stored geometry that happens to match the
/// default", because only the first should centre the window.
WindowGeometry? parseWindowGeometry({required String value}) =>
    RustLib.instance.api.crateApiWindowParseWindowGeometry(value: value);

/// Make a stored geometry safe to apply on the display available *now*.
///
/// Three separate hazards, each with its own rule:
///
/// * **The window is too small to use.** Clamped up to `min_width`/
///   `min_height`, which are the same floors the runner enforces. A stored
///   size below them can only come from another build or a hand-edited store.
/// * **The window is larger than the screen.** Clamped down, so a geometry
///   saved on a 4K monitor does not open off the edge of a laptop panel.
/// * **The window is off-screen entirely.** The rule is *visibility*, not
///   containment: a window may hang off an edge — users park them that way
///   deliberately — but at least [`MIN_VISIBLE`] pixels of it must be
///   reachable on each axis, or it cannot be dragged back. When that fails
///   the position is dropped, which the caller reads as "centre it".
///
/// Returns the geometry to apply; `None` for the position means centre.
FittedGeometry fitWindowGeometry({
  required WindowGeometry geometry,
  required double screenWidth,
  required double screenHeight,
  required double minWidth,
  required double minHeight,
}) => RustLib.instance.api.crateApiWindowFitWindowGeometry(
  geometry: geometry,
  screenWidth: screenWidth,
  screenHeight: screenHeight,
  minWidth: minWidth,
  minHeight: minHeight,
);

/// A geometry that is safe to apply. `x`/`y` are `None` when the stored
/// position was unusable and the window should be centred instead.
class FittedGeometry {
  final double? x;
  final double? y;
  final double width;
  final double height;
  final bool maximized;

  const FittedGeometry({
    this.x,
    this.y,
    required this.width,
    required this.height,
    required this.maximized,
  });

  @override
  int get hashCode =>
      x.hashCode ^
      y.hashCode ^
      width.hashCode ^
      height.hashCode ^
      maximized.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FittedGeometry &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y &&
          width == other.width &&
          height == other.height &&
          maximized == other.maximized;
}

/// A window's position, size, and whether it was maximized.
///
/// Coordinates are logical pixels in the primary display's space, matching
/// what `window_manager` reports and accepts.
class WindowGeometry {
  final double x;
  final double y;
  final double width;
  final double height;
  final bool maximized;

  const WindowGeometry({
    required this.x,
    required this.y,
    required this.width,
    required this.height,
    required this.maximized,
  });

  @override
  int get hashCode =>
      x.hashCode ^
      y.hashCode ^
      width.hashCode ^
      height.hashCode ^
      maximized.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WindowGeometry &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y &&
          width == other.width &&
          height == other.height &&
          maximized == other.maximized;
}
